import type { ReportDefinition } from '@proteticflow/shared';

export const reportRegistry: ReportDefinition[] = [
  {
    type: 'monthly_closing',
    title: 'Fechamento Mensal',
    description: 'Resumo financeiro mensal com breakdown por cliente.',
    outputKind: 'mixed',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'jobs_by_period',
    title: 'Trabalhos por Periodo',
    description: 'Lista de OS por periodo com filtros de data.',
    outputKind: 'table',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'productivity',
    title: 'Produtividade por Tecnico',
    description: 'OS concluidas, tempo medio e taxa de atraso por tecnico.',
    outputKind: 'table',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'quarterly_annual',
    title: 'Consolidado Trimestral/Anual',
    description: 'Consolidado por periodo com indicadores e graficos.',
    outputKind: 'mixed',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'inventory',
    title: 'Relatorio de Estoque',
    description: 'Posicao atual, movimentacoes e alertas de estoque.',
    outputKind: 'table',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'deliveries',
    title: 'Relatorio de Entregas',
    description: 'Entregas realizadas/falhas e tempo medio por rota.',
    outputKind: 'table',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'purchases',
    title: 'Relatorio de Compras',
    description: 'Ordens de compra por periodo e fornecedor.',
    outputKind: 'table',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'fiscal-revenue',
    title: 'Faturamento por Periodo',
    description: 'Receita por periodo com agrupamentos mensais, por dentista e por servico.',
    outputKind: 'table',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'fiscal-expenses',
    title: 'Despesas por Periodo',
    description: 'Despesas pagas por periodo com agrupamentos mensais, por fornecedor e categoria.',
    outputKind: 'table',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
  {
    type: 'fiscal-dre',
    title: 'DRE Simplificado',
    description: 'Receita menos despesas com resultado operacional e liquido.',
    outputKind: 'summary',
    supportsPdf: true,
    supportsCsv: true,
    supportsEmail: true,
    enabled: true,
  },
];

export function getReportDefinition(type: ReportDefinition['type']) {
  return reportRegistry.find((report) => report.type === type) ?? null;
}
